#!/usr/bin/env bash

# From: https://github.com/Toxblh/MTMR-presets/blob/master/minimalistic/mtmr/free_space.sh

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show the free space
#?? 1.0.0
##?
##? Usage:
##?   freespace
docs::parse "$@"

bash freespace.sh